# Generated by Django 5.0.6 on 2024-06-20 05:49

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0006_payment_orderdetail'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='pet',
            managers=[
                ('cpetobj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
